#####
## For explanation of YAML syntax, see https://learnxinyminutes.com/docs/yaml/
## In addition, ravshello supports a non-standard "!include" extension, e.g.:
##     KEY: !include /PATH/FILE
## Such inclusions will be handled recursively so use with care.
##
## WARNING about quoting strings:
## YAML doesn't require quoting simple strings but certain characters (e.g., ":"
## and "#") must be escaped if they're present so it's safer to just use quotes.
## (Ref: http://yaml.org/spec/1.2/spec.html#id2788859)

######
## Optionally specify login credentials for Ravello account to avoid prompting.

#ravelloUser: me@example.com
#ravelloPass: 'my cr@zy passw0rd'

######
## If present, *nickname* will be used as the ravshello 'user', overriding the
## default behavior of determining this from the system user (note that this
## nickname directive can in turn be overriden by the cmdline --nickname opt).

#nickname: myNickName

######
## If *appnameNickPrefix* is omitted, it defaults to "k:" (originally for
## "kerberos"). This is used in concert with *nickname* to build a prefix for
## all application names, i.e., a new app created by ravshello will be named:
##    <appnameNickPrefix><nickname>__<APPLICATION_NAME>
## Furthermore, in ravshello you will only be able to see apps whose names
## begin with:
##    <appnameNickPrefix><nickname>__
## Though of course in ravshello, it will hide the prefix so you'll only see:
##    <APPLICATION_NAME>

#appnameNickPrefix: 'k:'

######
## Optionally specify a default cost bucket (by name or numeric ID) in which to
## place all new apps created by ravshello. You will need execute permission on
## the cost bucket in order to associate an application with it.

#appCostBucket: myCostBucketNameOrId

######
## Optionally declare MULTIPLE sets of Ravello credentials and map them to
## profile names. The names are arbitrary and can be selected by use of
## the -u or --user cmdline option. Notes:
##  - *ravelloUser* is required.
##  - *ravelloPass* is not required. (Will be prompted for pass.)
##  - *nickname* is not required.
##  - *appnameNickPrefix* is not required.
##  - *appCostBucket* is not required.
##  - *defaultProfile* is not required.

#userProfiles:
#    bob:
#        ravelloUser: bob@example.com
#        ravelloPass: xxxxx
#        appCostBucket: QA
#        appnameNickPrefix: 'QA:'
#    ana:
#        ravelloUser: anabanana@example.com
#        ravelloPass: xxxxx
#        nickname: ana
#        appCostBucket: DEV
#        appnameNickPrefix: 'DEV:'
#    wow@example:
#        ravelloUser: wow@example.com
#    defaultProfile: ana

######
## Optionally specify text to be displayed when login fails. Declare as simple
## string or as a multiline literal block ("unableToLoginMsg: |") or multiline
## folded block ("unableToLoginMsg: >"). In any case, if this directive is
## present, it will replace the default message of:
## "If you're certain Ravello credentials are correct, try updating ravshello"

#unableToLoginMsg: Ohmg contact bob at the helpdesk!

######
## If present, *maxClientRetries* is passed to RavelloClient(). See --retries in
## help page for full explanation.

#maxClientRetries: 3

######
## If present, *sshKeyFile* is integrated into the ssh command reported to the
## user by ravshello's query_app_status command.

#sshKeyFile: /expected/path/to/ssh/priv/key

######
## If present, *eventsOfInterest* overrides rav-notify's default list of
## events to watch for. Remove existing lines and/or add new ones.

eventsOfInterest:
    - APP_TIMEOUT_AUTO_STOPPING
    - APP_TIMEOUT_AUTO_STOPPED
    - APPLICATION_TIMER_RESET
    - APPLICATION_DELETED
    - VM_STOPPED
    - VM_STARTED
    - VM_SNAPSHOTTING_AFTER_STOP
    - VM_FINISHED_SNAPSHOTTING

######
## If present, each cmdline in *preRunCommands* will be executed prior to
## any cmds present on argv and prior to entering the interactive shell but
## ONLY in admin mode and when no -s SCRIPTFILE option is present.

#preRunCommands:
#    - /blueprints refresh
#    - cd /apps
#    - ls
#    - (ADD AS MANY COMMANDS AS YOU WANT)

######
## Setting this boolean true changes the default behavior of prompting for
## missing Ravello credentials -- instead, ravshello will exit with login error.
## This can also be set true by use of --never-prompt-creds cmdline option.

#neverPromptCreds: false

######
## Optionally include additional config file(s). These must be the same format
## as above. Keys from included config files will overwrite keys from earlier
## files. Inclusion is not recursive (included files don't support `includes`),
## Globbing and tilde-expansion ARE supported.

#includes:
#    - ~/some/file
#    - /another/dir/*
